scrape_configs:
  - job_name: 'tidb'
    scrape_interval: 10s
    scrape_timeout: 10s
    profiling_config:
      pprof_config:
        profile:
          enabled: true
          seconds: 5
    targets: ['0.0.0.0:10080', '0.0.0.0:10081']
